/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tradingView_Database */

#ifndef _Included_tradingView_Database
#define _Included_tradingView_Database
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tradingView_Database
 * Method:    createConnection
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_createConnection
  (JNIEnv *, jclass);

/*
 * Class:     tradingView_Database
 * Method:    checkUser
 * Signature: (LtradingView/User;)Z
 */
JNIEXPORT jboolean JNICALL Java_tradingView_Database_checkUser
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tradingView_Database
 * Method:    checkUsername
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tradingView_Database_checkUsername
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tradingView_Database
 * Method:    insertUser
 * Signature: (LtradingView/User;)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_insertUser
  (JNIEnv *, jobject, jobject);

/*
 * Class:     tradingView_Database
 * Method:    getUserId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tradingView_Database_getUserId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tradingView_Database
 * Method:    getStockId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tradingView_Database_getStockId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tradingView_Database
 * Method:    checkIfStockExists
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tradingView_Database_checkIfStockExists
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tradingView_Database
 * Method:    addStock
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_addStock
  (JNIEnv *, jobject, jstring);

/*
 * Class:     tradingView_Database
 * Method:    checkIfOwnsExists
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_tradingView_Database_checkIfOwnsExists
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    addOwnsStock
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_addOwnsStock
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    insertBuying
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_insertBuying
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    getSymbol
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tradingView_Database_getSymbol
  (JNIEnv *, jobject, jint);

/*
 * Class:     tradingView_Database
 * Method:    checkHas
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_tradingView_Database_checkHas
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    getProfit
 * Signature: (ID)D
 */
JNIEXPORT jdouble JNICALL Java_tradingView_Database_getProfit
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     tradingView_Database
 * Method:    updateBuying
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_updateBuying
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    checkIfNotSold
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_tradingView_Database_checkIfNotSold
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    removeOwnsStock
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_removeOwnsStock
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    insertSelling
 * Signature: (IDI)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_insertSelling
  (JNIEnv *, jobject, jint, jdouble, jint);

/*
 * Class:     tradingView_Database
 * Method:    lastTransId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_tradingView_Database_lastTransId
  (JNIEnv *, jobject);

/*
 * Class:     tradingView_Database
 * Method:    insertTransaction
 * Signature: (DIII)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_insertTransaction
  (JNIEnv *, jobject, jdouble, jint, jint, jint);

/*
 * Class:     tradingView_Database
 * Method:    updateBalance
 * Signature: (ID)V
 */
JNIEXPORT void JNICALL Java_tradingView_Database_updateBalance
  (JNIEnv *, jobject, jint, jdouble);

/*
 * Class:     tradingView_Database
 * Method:    getBalance
 * Signature: (I)D
 */
JNIEXPORT jdouble JNICALL Java_tradingView_Database_getBalance
  (JNIEnv *, jobject, jint);

/*
 * Class:     tradingView_Database
 * Method:    getOwnedStocks
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tradingView_Database_getOwnedStocks
  (JNIEnv *, jobject, jint);

/*
 * Class:     tradingView_Database
 * Method:    getBought
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tradingView_Database_getBought
  (JNIEnv *, jobject, jint);

/*
 * Class:     tradingView_Database
 * Method:    getSold
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tradingView_Database_getSold
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
